package oop.practice;
import gen.*;

import org.antlr.v4.runtime.tree.ParseTree;

public class GravITyInterpreter extends GravITyBaseVisitor<Object> {
    /**
     * Method that displays the parse tree structure in the console.
     * @param tree The parse tree generated by ANTLR
     * @param level Indentation level for displaying the node hierarchy
     */

    public void printParseTree(ParseTree tree, int level) {
        String indent = " ".repeat(level * 2);

        System.out.println(indent + tree.getClass().getSimpleName() + ": " + tree.getText());

        for (int i = 0; i < tree.getChildCount(); i++) {
            printParseTree(tree.getChild(i), level + 1);
        }
    }
}

